name: find_me
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'

# main dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  introduction_screen: ^3.1.12
  smooth_page_indicator: ^1.1.0
  otp_text_field: ^1.1.3
  country_code_picker: ^3.0.0
  image_picker: ^1.0.4
  get_it: ^7.6.4
  dotted_border: ^2.1.0
  file_picker: ^6.0.0
  permission_handler: ^11.0.1
  device_info_plus: ^9.0.3
  intl: ^0.18.1
  shadow_overlay: ^1.0.5
  qr_flutter: ^4.1.0

# dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# assets path
flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/icons/
     - assets/onBoardingAssets/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/montserrat/Montserrat-Thin.ttf
          weight: 300
        - asset: fonts/montserrat/Montserrat-Light.ttf
          weight: 400
        - asset: fonts/montserrat/Montserrat-Regular.ttf
          weight: 500
        - asset: fonts/montserrat/Montserrat-Medium.ttf
          weight: 600
        - asset: fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 700
        - asset: fonts/montserrat/Montserrat-Bold.ttf
          weight: 800
        - asset: fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 900
  
  
  
